# Ticket: Connection
# Rename this file to .ini after filling in your MFLIX_DB_URI and your SECRET_KEY
# Do not surround the URI with quotes

[PROD]
SECRET_KEY = super_secret_key_you_should_change_rafaella
MFLIX_DB_URI = mongodb+srv://m220student:m220password@mflix.kqx03.mongodb.net/test
MFLIX_NS = sample_mflix

[TEST]
SECRET_KEY = super_secret_testing_key_rafaella
MFLIX_DB_URI = mongodb+srv://m220student:m220password@mflix.kqx03.mongodb.net/test
MFLIX_NS = sample_mflix
